[tool.poetry]
name = "pathstring"
version = "1.0.0"
description = "String with path operations."
readme = "README.rst"

authors = ["H. Turgut Uyar <uyar@tekir.org>"]
license = "BSD-3-Clause"

homepage = "https://pypi.org/project/pathstring/"
repository = "https://github.com/uyar/pathstring"

keywords = ["path"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

include = ["HISTORY.rst", "*.pyi", "tests/**/*.py"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^5.1.1"
flake8 = "^3.7.8"

[tool.black]
line-length = 96

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py{37,36,35}, pypy{36,35}, style
isolated_build = True

[testenv]
deps =
    pytest==5.1.1
commands =
    {posargs:pytest}

[testenv:pypy36]
basepython = pypy3.6

[testenv:style]
deps =
    flake8==3.7.8
commands =
    {posargs:flake8} pathstring.py
"""

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
