[tool.poetry]
name = "pathstring"
version = "1.0.0"
description = "String with path operations."
readme = "README.rst"

authors = ["H. Turgut Uyar <uyar@tekir.org>"]
license = "BSD-3-Clause"

homepage = "https://pypi.org/project/pathstring/"
repository = "https://github.com/uyar/pathstring"

keywords = ["path"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

include = ["*.pyi"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.1.1"
flake8 = "^3.7.8"
black = "^20.8b1"
tox = "^3.21.4"

[tool.black]
line-length = 96

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py{39,38,37,36}, pypy{37,36}, style
isolated_build = True

[testenv]
deps =
    pytest
commands =
    pytest {posargs:tests}

[testenv:style]
basepython = python3.8
deps =
    flake8
commands =
    flake8 pathstring.py
"""

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
